url: http://pingboard.github.io/json-api
safe: true
lsi: false
source: .
destination: ./public
exclude:
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: redcarpet
pygments: false
port: 9876

navigation:
- title: Overview
  url: /json-api/
- title: Format
  url: /json-api/format/
- title: Extending
  url: /json-api/extending/
- title: Examples
  url: /json-api/examples/
- title: FAQ
  url: /json-api/faq/
- title: About
  url: /json-api/about/
